sampler: &default
    dimensions: 2
    type: EXPRESSION
    expression:
      if(noise2(x,z)>simplex(x,z)*0.2,-1,noise(x,z))

    samplers:
      noise:
        type: LINEAR
        dimensions: 2
        max: 1
        min: -1
        sampler:
          type: CELLULAR
          dimensions: 2
          frequency: 0.2 / ${customization.yml:biome-distribution.continental-scale} / ${customization.yml:biome-distribution.global-scale}
          return: CellValue
      noise2:
        type: LINEAR
        dimensions: 2
        max: 1
        min: -2
        sampler:
          type: CELLULAR
          dimensions: 2
          frequency: 0.2 / ${customization.yml:biome-distribution.continental-scale} / ${customization.yml:biome-distribution.global-scale}
          return: Distance2Div
      simplex:
        type: OPEN_SIMPLEX_2
        dimensions: 2
        frequency: 0.002

stages:
  - type: REPLACE
    from: custom_biomes
    to:
      - OBSIDIAN_PEAKS: 1
      - GLASS_POOLS: 3
      - AMETHYST_HILLS: 1 # "Very rare"
      - ASH_SAVANNA_PLAINS: 1 # "Very rare"
      - BIRCH_TAIGA: 5 # "Rare"
      - BUSHLAND: 20 # Common
      - TROPICAL_JUNGLE: 5 # "Rare"
      - HOT_SPRINGS: 1 # "Very rare"
      - WHITE_CLIFFS: 1 # "Very rare"
      - SHIELD: 10 # "Uncommon"
      - FORESTED_HIGHLANDS: 20 # "Common"
      - CLOUD_FOREST: 1 # "Very rare"
      - GRAVEL_DESERT: 10 # "Uncommon"
      - DESERT_OASIS: 5 # "Rare"
      - WARPED_MESA: 1 # "Very rare"
      - MOONLIGHT_VALLEY: 10 # "Uncommon"
      - SAKURA_VALLEY: 1 # "Very rare"
      - LAVENDER_VALLEY: 5 # "Rare"
      - ICE_MARSH: 5 # "Rare"
      - GLACIAL_CHASM: 1 # "Very rare"
      - BLOOMING_VALLEY: 5 # "Rare"

    sampler: *default
